'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createActivityStats,cpuTotals,cpuPercent}=require('../src/main/activity-stats.cjs');
const {EventEmitter}=require('node:events');
test('CPU delta sums all processors and ignores first sample',()=>{const before=cpuTotals([{times:{idle:10,user:5,sys:5}},{times:{idle:10,user:5,sys:5}}]);const after=cpuTotals([{times:{idle:15,user:10,sys:5}},{times:{idle:15,user:10,sys:5}}]);assert.equal(cpuPercent(before,after),50);assert.equal(cpuPercent(before,before),0);});
test('disabled rows stop collection; input protocol accepts only count pairs',()=>{let children=[];const updates=[];function launch(){const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){child.ended=true;child.emit('exit',0);}};child.kill=()=>{};children.push(child);return child;}const stats=createActivityStats({platform:'win32',launch,onUpdate:v=>updates.push(v),system:{cpus:()=>[{times:{idle:1,user:1}}],totalmem:()=>100,freemem:()=>25}});stats.configure({statsClicks:true,statsRam:true});assert.equal(stats.snapshot().ram,75);children[0].stdout.emit('data',Buffer.from('bad\n2,3\n'));assert.equal(stats.snapshot().clicks,2);assert.equal(stats.snapshot().keys,3);stats.configure({statsClicks:false,statsKeys:false});assert.equal(children[0].ended,true);assert.equal(stats.snapshot().inputAvailable,false);stats.configure({statsKeys:true});children[1].stdout.emit('data',Buffer.from('1,4\n'));assert.equal(stats.snapshot().clicks,3);assert.equal(stats.snapshot().keys,7);stats.dispose();assert.equal(children[1].ended,true);});
test('unrelated setting saves preserve CPU sampling baseline',()=>{let calls=0;const stats=createActivityStats({platform:'linux',system:{cpus:()=>{calls++;return [{times:{idle:1,user:1}}];},totalmem:()=>100,freemem:()=>25}});stats.configure({statsCpu:true});stats.configure({statsCpu:true,note:'changed'});stats.configure({statsCpu:true,statsPosition:'left'});stats.configure({statsCpu:true,statsKeys:true});assert.equal(calls,1);stats.configure({statsCpu:true,statsRam:true});assert.equal(calls,2);stats.dispose();});
test('daily totals persist on clean exit and reset at local midnight without adding old cumulative input',async()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'ogle-totals-'));let date=new Date(2026,8,30,23,59,59),child;
 function launch(){child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end(){child.stdout.emit('data',Buffer.from('5,9\n'));child.emit('exit',0);}};child.kill=()=>{};return child;}
 const stats=createActivityStats({dataDir,now:()=>date,platform:'win32',launch});stats.configure({statsClicks:true});child.stdout.emit('data',Buffer.from('3,7\n'));await stats.dispose();let saved=JSON.parse(fs.readFileSync(path.join(dataDir,'activity-totals.json')));assert.deepEqual(saved,{date:'2026-09-30',clicks:5,keys:9});
 const next=createActivityStats({dataDir,now:()=>date,platform:'win32',launch});assert.equal(next.snapshot().keys,9);next.configure({statsKeys:true});child.stdout.emit('data',Buffer.from('2,4\n'));assert.equal(next.snapshot().keys,13);date=new Date(2026,9,1,0,0,0);child.stdout.emit('data',Buffer.from('3,5\n'));assert.equal(next.snapshot().clicks,1);assert.equal(next.snapshot().keys,1);await next.dispose();saved=JSON.parse(fs.readFileSync(path.join(dataDir,'activity-totals.json')));assert.equal(saved.date,'2026-10-01');assert.equal(saved.clicks,3);assert.equal(saved.keys,5);
 const tomorrow=createActivityStats({dataDir,now:()=>new Date(2026,9,2),platform:'linux'});assert.equal(tomorrow.snapshot().keys,0);await tomorrow.dispose();fs.rmSync(dataDir,{recursive:true,force:true});
});
test('optional hardware sampling remains off by default',async()=>{let samples=0,closed=false;const stats=createActivityStats({platform:'linux',hardware:{async sample(){samples++;return {cpuTemp:null,gpu:37,gpuClock:1200};},dispose(){closed=true;}}});stats.configure({statsCpu:true});assert.equal(samples,0);stats.configure({statsCpu:true,statsGpu:true});await new Promise(resolve=>setImmediate(resolve));assert.equal(samples,1);assert.equal(stats.snapshot().gpu,37);stats.configure({statsCpu:true,statsGpu:true,note:'draft'});assert.equal(samples,1);await stats.dispose();assert.equal(closed,true);});
