'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {ActivityTracker,ChatGPTActivity}=require('../src/main/chatgpt-activity.cjs');
const idle={available:true,working:false,complete:false,failed:false};
function fixture(){const events=[];return{events,tracker:new ActivityTracker(event=>events.push(event.state))};}
test('baseline completed history emits nothing; observed work requires stable completion',()=>{const {tracker,events}=fixture();tracker.sample({...idle,complete:true});tracker.sample({...idle,working:true});tracker.sample({...idle,complete:true});assert.deepEqual(events,['working']);tracker.sample({...idle,complete:true});tracker.sample({...idle,complete:true});assert.deepEqual(events,['working','done']);});
test('stop disappearance without positive final controls never completes',()=>{const {tracker,events}=fixture();tracker.sample({...idle,working:true});tracker.sample(idle);tracker.sample(idle);assert.deepEqual(events,['working']);});
test('old assistant controls while stop button appears cannot fabricate completion',()=>{const {tracker,events}=fixture();tracker.sample({...idle,working:true,complete:true});tracker.sample({...idle,complete:true});tracker.sample({...idle,complete:true});assert.deepEqual(events,['working']);tracker.sample({...idle,working:true});tracker.sample({...idle,complete:true});tracker.sample({...idle,complete:true});assert.deepEqual(events,['working','done']);});
test('navigation and context loss never become completion',()=>{const {tracker,events}=fixture();tracker.sample({...idle,working:true});tracker.sample({available:false});tracker.reset();tracker.sample({...idle,complete:true});tracker.sample({...idle,complete:true});assert.deepEqual(events,['working','idle']);});
test('explicit error only fails an observed running generation once',()=>{const {tracker,events}=fixture();tracker.sample({...idle,failed:true});tracker.sample({...idle,working:true});tracker.sample({...idle,failed:true});tracker.sample({...idle,failed:true});assert.deepEqual(events,['working','failed']);});
test('poll is bounded and ignores stale result after navigation',async()=>{class Contents extends EventEmitter{isDestroyed(){return false;}isLoadingMainFrame(){return false;}getURL(){return'https://chatgpt.com/';}executeJavaScript(){this.calls=(this.calls||0)+1;return new Promise(resolve=>this.resolve=resolve);}}const contents=new Contents(),events=[],observer=new ChatGPTActivity(contents,e=>events.push(e.state),60000);const first=observer.poll();await observer.poll();assert.equal(contents.calls,1);contents.emit('did-start-navigation',{},'https://chatgpt.com/c/test',false,true);contents.resolve({...idle,working:true});await first;assert.deepEqual(events,[]);observer.dispose();assert.equal(contents.listenerCount('did-start-navigation'),0);});
