'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {ClaudeBridge}=require('../src/main/claude-bridge.cjs');
const ID='7b04f05e-7a12-4a37-a535-5a12e50a64dd';
async function fixture(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-claude-history-')),home=path.join(dir,'home'),data=path.join(dir,'data'),project=path.join(home,'.claude','projects','C--project'),file=path.join(project,ID+'.jsonl');await fs.mkdir(project,{recursive:true});await fs.writeFile(file,JSON.stringify({type:'user',cwd:'C:\\project',message:{content:'fixture prompt'}})+'\n'+JSON.stringify({type:'custom-title',customTitle:'Original',sessionId:ID})+'\n');const b=new ClaudeBridge({homeDir:home,dataDir:data,env:{}});return {dir,home,data,project,file,b,cleanup:async()=>{b.dispose();await fs.rm(dir,{recursive:true,force:true});}};}
test('Claude rename uses official title record, keeps transcript and modification time',async()=>{const f=await fixture();try{const before=await fs.readFile(f.file,'utf8'),stat=await fs.stat(f.file);assert.equal((await f.b.listThreads()).threads[0].title,'Original');await f.b.renameThread(ID,'New title');const after=await fs.readFile(f.file,'utf8');assert.ok(after.startsWith(before));assert.deepEqual(JSON.parse(after.trim().split('\n').at(-1)),{type:'custom-title',customTitle:'New title',sessionId:ID});assert.ok(Math.abs((await fs.stat(f.file)).mtimeMs-stat.mtimeMs)<1);assert.equal((await f.b.listThreads()).threads[0].title,'New title');}finally{await f.cleanup();}});
test('Claude remove archives complete transcript and restore preserves project and date',async()=>{const f=await fixture();try{const text=await fs.readFile(f.file,'utf8'),stat=await fs.stat(f.file);await f.b.removeThread(ID);await assert.rejects(fs.stat(f.file),{code:'ENOENT'});assert.ok((await fs.stat(f.project)).isDirectory());assert.deepEqual((await f.b.listThreads()).threads,[]);const archived=await f.b.listArchivedThreads();assert.equal(archived.threads[0].title,'Original');await f.b.restoreThread(ID);assert.equal(await fs.readFile(f.file,'utf8'),text);assert.ok(Math.abs((await fs.stat(f.file)).mtimeMs-stat.mtimeMs)<1);assert.equal((await f.b.listThreads()).threads.length,1);assert.deepEqual((await f.b.listArchivedThreads()).threads,[]);}finally{await f.cleanup();}});
test('Claude management rejects invalid names, active sessions, ambiguous IDs and restore collisions',async()=>{const f=await fixture();try{await assert.rejects(f.b.renameThread('../file','x'),/Invalid/);await assert.rejects(f.b.renameThread(ID,'\n'),/name/);f.b.sessions.set('active',{resume:ID});await assert.rejects(f.b.removeThread(ID),/Close/);await assert.rejects(f.b.renameThread(ID,'x'),/Close/);f.b.sessions.clear();const other=path.join(path.dirname(f.project),'other');await fs.mkdir(other);await fs.copyFile(f.file,path.join(other,ID+'.jsonl'));await assert.rejects(f.b.removeThread(ID),/ambiguous/);await fs.unlink(path.join(other,ID+'.jsonl'));await f.b.removeThread(ID);await fs.writeFile(f.file,'new contents');await assert.rejects(f.b.restoreThread(ID),{code:'EEXIST'});assert.equal(await fs.readFile(f.file,'utf8'),'new contents');assert.equal((await f.b.listArchivedThreads()).threads.length,1);}finally{await f.cleanup();}});
test('Claude history never follows linked files or project directories',async t=>{const f=await fixture();try{const outside=path.join(f.dir,'outside');await fs.mkdir(outside);const target=path.join(outside,ID+'.jsonl');await fs.copyFile(f.file,target);await fs.unlink(f.file);try{await fs.symlink(outside,f.project+'-linked',process.platform==='win32'?'junction':'dir');}catch(error){if(error.code==='EPERM'){t.skip('Symlink permission unavailable');return;}throw error;}assert.deepEqual((await f.b.listThreads()).threads,[]);await assert.rejects(f.b.removeThread(ID),/not found/);assert.ok((await fs.stat(target)).isFile());}finally{await f.cleanup();}});
test('Claude auth status is bounded, cached and returns only nonsecret state',async()=>{let calls=0;const b=new ClaudeBridge({authRunner:async(file,args,options)=>{calls++;assert.deepEqual(args,['auth','status']);assert.equal(options.windowsHide,true);assert.equal(options.timeout,3000);return {stdout:JSON.stringify({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty',email:'private@example.test',accessToken:'secret'})};}});try{assert.deepEqual(await b.authStatus('claude.exe'),{loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty'});await b.authStatus('claude.exe');assert.equal(calls,1);}finally{b.dispose();}});
