'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {CodexBridge,DesktopIpc,desktopRuntime}=require('../src/main/codex-bridge.cjs');
function state(type='active'){const turn={turnId:'real-turn',status:'inProgress'};Object.defineProperty(turn,'items',{get(){throw new Error('Message projection must not occur');}});return {id:'t',threadRuntimeStatus:{type},turnHistory:{kind:'canonical',history:{entitiesByKey:{old:{turnId:'older'},last:turn},islands:[{entries:[{value:'old'},{value:'last'}]}]}}};}
function deliver(ipc,change){ipc._receive({type:'broadcast',method:'thread-stream-state-changed',version:11,params:{hostId:'local',conversationId:'t',change}});}
test('runtime metadata is authoritative and does not read message items',()=>{assert.deepEqual(desktopRuntime(state()),{running:true,turnId:'real-turn'});assert.deepEqual(desktopRuntime(state('idle')),{running:false,turnId:'real-turn'});assert.equal(desktopRuntime(state('unknown')),null);assert.equal(desktopRuntime(null),null);});
test('runtime-only desktop snapshot and patches skip projection and debounce',async()=>{const ipc=new DesktopIpc({runtimeOnly:true});ipc._write=()=>{};ipc._emitState=()=>{throw new Error('No projection allowed');};let snapshots=0;ipc.on('snapshot',()=>snapshots++);const pending=ipc.readRuntime('t','owner');deliver(ipc,{type:'snapshot',revision:1,conversationState:state()});assert.deepEqual(await pending,{running:true,turnId:'real-turn'});deliver(ipc,{type:'patches',baseRevision:1,revision:2,patches:[{op:'replace',path:['threadRuntimeStatus','type'],value:'idle'}]});assert.deepEqual(await ipc.readRuntime('t','owner'),{running:false,turnId:'real-turn'});assert.equal(snapshots,2);assert.equal(ipc.timers.size,0);assert.equal(ipc.signatures.size,0);ipc.close();});
test('snapshot wait cancels immediately on close and removes listeners',async()=>{const ipc=new DesktopIpc({runtimeOnly:true});ipc._write=()=>{};const pending=ipc.readRuntime('t','owner');ipc.close();await assert.rejects(pending,/closed/);assert.equal(ipc.listenerCount('snapshot'),0);assert.equal(ipc.listenerCount('disconnected'),0);});
test('bridge uses independent bounded clients and closes on success or failure',async()=>{const desktop=new EventEmitter();desktop.followed=new Set(['selected-task']);const clients=[];let fail=false;const bridge=new CodexBridge({spawnProcess:()=>{},desktop,runtimeClientFactory:()=>{const client={closed:false,async owner(id){assert.equal(id,'t');if(fail)throw new Error('owner gone');return 'owner';},async readRuntime(id,owner){assert.equal(owner,'owner');return {running:true,turnId:'turn'};},close(){this.closed=true;}};clients.push(client);return client;}});assert.equal(bridge.activity,null);assert.deepEqual(await bridge._readActivityRuntime('t'),{running:true,turnId:'turn'});assert.equal(clients[0].closed,true);fail=true;assert.equal(await bridge._readActivityRuntime('t'),null);assert.equal(clients[1].closed,true);assert.deepEqual([...desktop.followed],['selected-task']);assert.equal(bridge.runtimeProbes.size,0);bridge._dispose();});
test('disposal closes every pending probe and late replies cannot escape generation guard',async()=>{const clients=[];const bridge=new CodexBridge({spawnProcess:()=>{},desktop:null,runtimeClientFactory:()=>{let finish;const client={async owner(){return 'owner';},readRuntime(){return new Promise(resolve=>{finish=resolve;});},close(){this.closed=true;finish?.({running:true,turnId:'late'});}};clients.push(client);return client;}});const one=bridge._readActivityRuntime('a'),two=bridge._readActivityRuntime('b');await new Promise(resolve=>setImmediate(resolve));assert.equal(await bridge._readActivityRuntime('c'),null);assert.equal(clients.length,2);bridge._dispose();assert.equal(await one,null);assert.equal(await two,null);assert.ok(clients.every(client=>client.closed));assert.equal(bridge.runtimeProbes.size,0);});
test('active status without a current in-progress turn does not reuse a completed turn id',()=>{assert.deepEqual(desktopRuntime({threadRuntimeStatus:{type:'active'},turns:[{id:'old',status:'completed'}]}),{running:true});});
