'use strict';
const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts'),profile=path.join(out,`compact-profile-${Date.now()}`);
  fs.mkdirSync(profile,{recursive:true});
  const env={...process.env,PETDOCK_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
  const executable=process.env.PETDOCK_TEST_EXE;
  const app=await electron.launch({...(executable?{executablePath:path.resolve(executable),args:[]}:{args:[root]}),env}),errors=[],checks={};
  try{
    const page=await app.firstWindow();page.on('pageerror',err=>errors.push(err.message));
    await app.evaluate(({screen})=>{global.__compactCursor={x:0,y:0};screen.getCursorScreenPoint=()=>global.__compactCursor;});
    await page.waitForSelector('#status-dot.ready',{state:'attached',timeout:60000});
    await page.waitForSelector('#compact-thread-list .compact-thread',{state:'attached',timeout:60000});
    const click=selector=>page.locator(selector).evaluate(el=>el.click());
    const mode=()=>page.evaluate(()=>state.mode);
    const bounds=()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds());
    const hover=async selector=>{const rect=await page.locator(selector).boundingBox();assert.ok(rect,`${selector} is visible`);const b=await bounds(),point={x:rect.x+rect.width/2,y:rect.y+rect.height/2};await app.evaluate((_,p)=>{global.__compactCursor=p;},{x:b.x+point.x,y:b.y+point.y});await page.mouse.move(point.x,point.y);};
    const outside=async()=>{await app.evaluate(()=>{global.__compactCursor={x:0,y:0};});await page.mouse.move(1,1);await page.waitForTimeout(300);};
    const capture=async name=>{
      const data=await app.evaluate(async({BrowserWindow,desktopCapturer})=>{const win=BrowserWindow.getAllWindows()[0];const sources=await desktopCapturer.getSources({types:['window'],thumbnailSize:{width:1520,height:1640}});return sources.find(s=>s.id===win.getMediaSourceId())?.thumbnail.toPNG().toString('base64');});
      if(data)fs.writeFileSync(path.join(out,`compact-${name}.png`),Buffer.from(data,'base64'));
    };
    assert.equal(await mode(),'idle');assert.equal((await bounds()).width,220);
    assert.equal(await page.locator('.brand,#connection,#auto-expand').count(),0);
    assert.equal(await page.locator('#composer').isHidden(),true);
    await capture('idle');
    // Use real renderer pointer movement and a matching OS-boundary cursor, including after resize.
    await hover('#pet');await page.waitForTimeout(450);
    assert.equal(await mode(),'idle','Pet hover must not reveal the toolbar');
    await hover('#bar-orb');
    await page.waitForFunction(()=>state.mode==='reveal',null,{timeout:1500});
    await hover('.toolbar');
    await page.waitForTimeout(3300);
    assert.equal(await mode(),'reveal','Long hovering must never open a full panel');
    assert.equal((await bounds()).width,600);assert.ok((await bounds()).height<=200);
    assert.equal(await page.locator('#composer').isHidden(),true);
    assert.equal(await page.locator('.toolbar').evaluate(el=>el.getBoundingClientRect().height),36);
    assert.equal(await page.locator('.tool.selected').evaluate(el=>getComputedStyle(el).boxShadow),'none');
    assert.deepEqual(await page.locator('.toolbar>.tool').evaluateAll(nodes=>nodes.slice(-2).map(n=>n.dataset.panel)),['terminal','shortcuts']);
    assert.equal(await page.locator('#collapse').textContent(),'⌃');
    checks.hoverOnlyRevealsBar=true;await capture('revealed');
    await click('#conversation-picker-toggle');await page.waitForFunction(()=>state.mode==='picker');
    assert.equal((await bounds()).height,470);
    const first=page.locator('#compact-thread-list .compact-thread').first(),selectedId=await first.getAttribute('data-thread-id');
    await first.evaluate(el=>el.click());
    await page.waitForFunction(id=>state.selected?.id===id && document.getElementById('activity').textContent!=='Loading conversation…',selectedId);
    assert.equal(await mode(),'quick');assert.equal((await bounds()).height,350);
    assert.equal(await page.locator('#composer').count(),1);
    assert.equal(await page.locator('#composer').isVisible(),true);
    await page.locator('#prompt').fill('Local compact draft — do not send');
    await page.locator('#prompt').evaluate(el=>el.blur());
    await outside();await hover('.toolbar');await page.waitForTimeout(3300);
    assert.equal(await mode(),'quick','Quick composer stays compact despite hovering or leaving');
    checks.pickerSelectsTaskAndQuickStaysLocked=true;await capture('quick');
    await click('[data-panel="editor"]');assert.equal(await mode(),'expand');assert.equal((await bounds()).height,820);
    assert.equal(await page.locator('#conversation-strip').isHidden(),true);
    assert.equal(await page.locator('#conversation-picker').isHidden(),true);
    assert.equal(await page.locator('#collapse').textContent(),'⌄');
    checks.toolsOpenFullPanel=true;
    const top=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop());
    await click('#always-top');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),!top);
    await click('#always-top');
    checks.alwaysOnTopRestored=true;
    await click('#settings-button');await page.locator('[data-setting="autoExpand"]').uncheck();
    assert.equal(await page.locator('#panel-pin').isHidden(),true);
    await click('#collapse');await hover('#bar-orb');await page.waitForTimeout(500);
    assert.equal(await mode(),'idle');
    await click('#bar-orb');assert.equal(await mode(),'reveal');
    await click('#conversation-name');assert.equal(await mode(),'quick');
    assert.equal(await page.locator('#prompt').inputValue(),'Local compact draft — do not send');
    checks.autoOffAndDraftPreserved=true;
    // A still-focused prompt folds after five seconds. Real mouse/key activity restarts that deadline.
    await page.locator('#prompt').focus();
    await page.locator('#prompt').evaluate(async el=>{
      const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);
      const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
      const clipboard=new DataTransfer();clipboard.items.add(new File([blob],'idle-fixture.png',{type:'image/png'}));
      el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:clipboard}));
    });
    await page.waitForFunction(()=>window.PetDockAttachments.hasImages()&&!window.PetDockAttachments.isBusy());
    await page.waitForTimeout(2800);await hover('#prompt');
    await page.waitForTimeout(2800);assert.equal(await mode(),'quick','Mouse movement resets quick idle');
    await page.locator('#prompt').press('ArrowLeft');
    await page.waitForTimeout(2800);assert.equal(await mode(),'quick','Key activity resets quick idle');
    await page.waitForFunction(()=>state.mode==='idle',null,{timeout:3000});
    assert.equal(await page.locator('#prompt').inputValue(),'Local compact draft — do not send');
    assert.equal(await page.evaluate(()=>window.PetDockAttachments.hasImages()),true,'Idle preserves pasted images');
    await click('#bar-orb');await click('#conversation-name');
    assert.equal(await page.locator('#prompt').inputValue(),'Local compact draft — do not send');
    assert.equal(await page.evaluate(()=>window.PetDockAttachments.hasImages()),true);
    checks.quickFiveSecondActivityDeadlinePreservesDraftAndImages=true;
    await page.locator('#prompt').fill('');await page.evaluate(()=>window.PetDockAttachments.clear());
    assert.deepEqual(errors,[]);
    const report={at:new Date().toISOString(),checks,rendererErrors:errors,profile,executable:executable || 'source',limitations:'Native cursor polling matched actual Playwright renderer pointer positions at the OS boundary for deterministic hover tests. No prompts sent, login changes, or remote installs.'};
    fs.writeFileSync(path.join(out,'compact-runtime.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  }finally{await app.close();}
})().catch(err=>{console.error(err);process.exitCode=1;});
