'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {PetLibrary}=require('../src/main/pet-library.cjs');
async function fixture(){const folder=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-pet-cache-')),source=path.join(folder,'codex'),destination=path.join(folder,'local'),bundled=path.join(folder,'bundled');await fs.mkdir(path.join(source,'fixture'),{recursive:true});const sprite=await fs.readFile(path.join(__dirname,'../assets/pets/lago-realistic/spritesheet.webp'));await fs.writeFile(path.join(source,'fixture','spritesheet.webp'),sprite);await fs.writeFile(path.join(source,'fixture','pet.json'),JSON.stringify({id:'fixture',displayName:'Fixture',spriteVersionNumber:2,spritesheetPath:'spritesheet.webp',author:'Creator'}));return {folder,source,destination,bundled,sprite,options:{destination,codexSource:source}};}
test('unchanged repeated lists and process restarts avoid full sprite reads and hashes',async()=>{
 const f=await fixture();try{const library=new PetLibrary(f.bundled,f.options);assert.equal((await library.refresh()).updated,1);const cold={...library.metrics};await library.list();await library.refresh();assert.equal(library.metrics.fullSpriteReads,cold.fullSpriteReads);assert.equal(library.metrics.hashes,cold.hashes);const restart=new PetLibrary(f.bundled,f.options);const result=await restart.refresh();assert.equal(result.updated,0);assert.equal(restart.metrics.hashes,0);assert.equal(restart.metrics.fullSpriteReads,0);assert.equal(result.pets[0].config.author,'Creator');console.log(JSON.stringify({cold,restart:restart.metrics,oldStartupFullReads:3,newWarmStartupFullReads:0}));}finally{await fs.rm(f.folder,{recursive:true,force:true});}
});
test('changed sprites invalidate the metadata cache and sync changed bytes',async()=>{
 const f=await fixture();try{const library=new PetLibrary(f.bundled,f.options);await library.refresh();const first=(await library.list())[0].spriteUrl;const changed=Buffer.concat([f.sprite,Buffer.from('new-fixture-version')]);await fs.writeFile(path.join(f.source,'fixture','spritesheet.webp'),changed);const result=await library.refresh();assert.equal(result.updated,1);assert.notEqual(result.pets[0].spriteUrl,first);const manifest=JSON.parse(await fs.readFile(path.join(f.destination,'fixture','pet.json'),'utf8'));assert.deepEqual(await fs.readFile(path.join(f.destination,'fixture',manifest.spritesheetPath)),changed);}finally{await fs.rm(f.folder,{recursive:true,force:true});}
});
test('tampered manifests and cache entries cannot cause arbitrary sprite path reads',async()=>{
 const f=await fixture();try{const library=new PetLibrary(f.bundled,f.options);await library.refresh();await fs.writeFile(path.join(f.destination,'fixture','pet.json'),JSON.stringify({id:'fixture',spriteVersionNumber:2,spritesheetPath:'../outside.webp'}));await fs.writeFile(path.join(f.destination,'.pet-index.json'),JSON.stringify({version:1,entries:[['/outside.webp',{fingerprint:'anything',hash:'a'.repeat(64),config:{spritesheetPath:'../outside.webp'}}]]}));const restart=new PetLibrary(f.bundled,f.options);assert.equal((await restart.list()).length,0);}finally{await fs.rm(f.folder,{recursive:true,force:true});}
});
