'use strict';
const { _electron: electron } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async()=>{
  const root=path.resolve(__dirname,'..'), profile=path.join(root,'artifacts',`shortcuts-profile-${Date.now()}`);
  fs.mkdirSync(profile,{recursive:true});
  const settingsFile=path.join(profile,'settings.json');
  fs.writeFileSync(settingsFile,JSON.stringify({compactChatTarget:'codex',autoStart:false,autoExpand:false,linksLayoutVersion:2,shortcuts:[{id:'group-a',name:'Group A',kind:'group',path:null,parentId:null},{id:'group-b',name:'Group B',kind:'group',path:null,parentId:'group-a'},{id:'link-a',name:'Example',path:'https://example.com/',kind:'url',parentId:null}],shortcutsView:'details'}));
  const env={...process.env,PETDOCK_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
  const app=await electron.launch(process.env.PETDOCK_TEST_EXE?{executablePath:process.env.PETDOCK_TEST_EXE,args:[],env}:{args:[root],env});
  try{
    const page=await app.firstWindow();
    await app.evaluate(({BrowserWindow,screen})=>{const win=BrowserWindow.getAllWindows()[0];win.webContents.setBackgroundThrottling(false);win.hide();screen.getCursorScreenPoint=()=>({x:-9999,y:-9999});});
    await page.locator('.links-content').waitFor({state:'attached',timeout:60000});
    await page.waitForFunction(()=>state.settings.compactChatTarget==='codex'&&!DockLayoutTransition.busy);
    await page.evaluate(()=>switchPanel('shortcuts'));
    const stored=()=>JSON.parse(fs.readFileSync(settingsFile,'utf8'));
    const drop=async(id,selector)=>page.locator(selector).evaluate((el,id)=>{const dt=new DataTransfer();dt.setData('application/x-petdock-link',id);el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));},id);
    await drop('link-a','.links-entry[data-id="group-b"] > .links-row');
    await page.waitForTimeout(250);assert.equal(stored().shortcuts.find(x=>x.id==='link-a').parentId,'group-b');
    await drop('group-a','.links-entry[data-id="group-b"] > .links-row');
    await page.waitForTimeout(150);assert.equal(stored().shortcuts.find(x=>x.id==='group-a').parentId,null);
    await drop('link-a','.links-content');
    await page.waitForTimeout(150);assert.equal(stored().shortcuts.find(x=>x.id==='link-a').parentId,null);
    await page.locator('.links-entry[data-id="link-a"] button[title="Rename or edit target"]').click();
    await page.getByLabel('Display name',{exact:true}).fill('My example');
    await page.locator('.links-form [data-submit]').click();
    await page.waitForTimeout(150);assert.equal(stored().shortcuts.find(x=>x.id==='link-a').alias,'My example');
    await page.locator('#shortcuts-panel .subtoolbar button').filter({hasText:'＋ Add'}).click();
    await page.getByLabel('Path or URL',{exact:true}).fill(root);
    await page.locator('.links-form [data-submit]').click();
    await page.waitForTimeout(250);assert.ok(stored().shortcuts.some(x=>x.kind==='folder'&&x.path===root),'Unified Add accepts a local folder path');
    await page.getByLabel('Toggle link view').click();
    await page.waitForTimeout(150);assert.equal(stored().shortcutsView,'icons');
    await page.locator('.links-entry[data-id="group-a"] > .links-row .links-open').click();
    await page.locator('.links-entry[data-id="group-b"] > .links-row').evaluate(el=>{const dt=new DataTransfer();dt.setData('text/uri-list','https://www.electronjs.org/');el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});
    await page.waitForTimeout(300);
    assert.ok(stored().shortcuts.some(x=>x.kind==='url'&&x.parentId==='group-b'&&x.path.includes('electronjs.org')),'External URL drop persisted inside target group');
    await page.locator('.links-entry[data-id="group-b"] > .links-row button[title^="Remove group"]').click();
    await page.getByRole('dialog',{name:'Confirm removal'}).getByRole('button',{name:'Remove',exact:true}).click();
    await page.waitForTimeout(150);
    assert.ok(stored().shortcuts.some(x=>x.path?.includes('electronjs.org')&&x.parentId==='group-a'),'Removing group preserves its links');
    await page.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='drop-fixture';input.hidden=true;document.body.append(input);});
    await page.locator('#drop-fixture').setInputFiles(path.join(root,'README.md'));
    await page.locator('.links-content').evaluate(el=>{const dt=new DataTransfer();dt.items.add(document.getElementById('drop-fixture').files[0]);el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});
    await page.waitForTimeout(350);
    assert.ok(stored().shortcuts.some(x=>x.kind==='file'&&x.path.endsWith('README.md')),'Native file drop resolves through preload and persists');
    await page.screenshot({path:path.join(root,'artifacts/shortcuts-ui.png')});
    console.log(JSON.stringify({nestedDrop:true,cycleRejected:true,rootMove:true,aliasPersisted:true,viewPersisted:true,urlDrop:true,nativeFileDrop:true,groupDeletionPreservesChildren:true,profile},null,2));
  }finally{await app.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
