'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {zipSync}=require('fflate'),{UpdateManager,LATEST}=require('../src/main/update-manager.cjs'),{validateDistributionZip}=require('../src/main/update-distribution.cjs'),{prepareHandoff,assertInstallDirectory}=require('../src/main/update-handoff.cjs');
async function fixture({badHash=false,unsafe=false}={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-update-test-'));const version='0.7.6',name='Ogle-'+version+'-win32-x64.zip',zip=zipSync(unsafe?{'../Ogle.exe':Buffer.from('x')}: {'Ogle-win32-x64/Ogle.exe':Buffer.from('exe'),'Ogle-win32-x64/resources/app.asar':Buffer.from('asar')}),digest=crypto.createHash('sha256').update(zip).digest('hex'),url='https://github.com/Tihkal96/Ogle/releases/download/v'+version+'/'+name;const metadata={tag_name:'v'+version,draft:false,prerelease:false,assets:[{name,size:zip.length,browser_download_url:url,digest:'sha256:'+digest},{name:name+'.sha256',browser_download_url:url+'.sha256'}]};let extracts=0;const fetcher=async target=>new Response(target===LATEST?JSON.stringify(metadata):target.endsWith('.sha256')?(badHash?'0'.repeat(64):digest)+'  '+name:zip);const manager=new UpdateManager({currentVersion:'0.7.5',dataDir:dir,fetcher,extractor:async(_zip,destination)=>{extracts++;await fs.mkdir(path.join(destination,'Ogle-win32-x64','resources'),{recursive:true});await fs.writeFile(path.join(destination,'Ogle-win32-x64','Ogle.exe'),'exe');await fs.writeFile(path.join(destination,'Ogle-win32-x64','resources','app.asar'),'asar');}});return{dir,manager,metadata,zip,get extracts(){return extracts;},cleanup:()=>fs.rm(dir,{recursive:true,force:true})};}
test('official update is checked, verified and staged once without replacing current files',async()=>{const f=await fixture();try{assert.equal((await f.manager.check()).available,true);const first=f.manager.prepare(),second=f.manager.prepare();assert.equal(first,second);const result=await first;assert.equal(result.ready,true);assert.equal(f.extracts,1);assert.ok(result.exePath.startsWith(f.dir));assert.equal(await fs.readFile(result.exePath,'utf8'),'exe');}finally{await f.cleanup();}});
test('checksum mismatch refuses extraction and cleans partial staging',async()=>{const f=await fixture({badHash:true});try{await assert.rejects(f.manager.prepare(),/disagree|verification/i);assert.equal(f.extracts,0);assert.deepEqual(await fs.readdir(path.join(f.dir,'updates')).catch(()=>[]),[]);}finally{await f.cleanup();}});
test('release assets cannot point outside the official repository',async()=>{const f=await fixture();try{f.metadata.assets[0].browser_download_url='https://example.com/'+f.metadata.assets[0].name;await assert.rejects(f.manager.check(),/official/);}finally{await f.cleanup();}});
test('unsafe ZIP paths are rejected before Windows extraction',async()=>{const f=await fixture({unsafe:true});try{await assert.rejects(f.manager.prepare(),/Unsafe/);assert.equal(f.extracts,0);}finally{await f.cleanup();}});
test('handoff preserves install path, retains backup, and never removes the profile',async()=>{const f=await fixture();try{const ready=await f.manager.prepare(),install=path.join(f.dir,'installed');await fs.cp(ready.folder,install,{recursive:true});const handoff=await prepareHandoff({currentExe:path.join(install,'Ogle.exe'),stagedFolder:ready.folder,dataDir:f.dir,pid:process.pid,launch:false});const script=await fs.readFile(handoff.script,'utf8');assert.equal(handoff.target,install);assert.match(script,/Move-Item -LiteralPath \$target -Destination \$backup/);assert.match(script,/StartTime.Ticks/);assert.ok(!script.includes('Remove-Item'));assert.equal(await fs.readFile(path.join(install,'Ogle.exe'),'utf8'),'exe');assert.equal(await fs.readFile(path.join(handoff.candidate,'Ogle.exe'),'utf8'),'exe');await assert.rejects(assertInstallDirectory(path.parse(install).root),/location/);}finally{await f.cleanup();}});

test('Windows-normalized ZIP paths and device names are rejected',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-zip-negative-'));try{for(const leaf of ['.. /escape','name.','name ','COM1.txt','NUL','aux.dat','sub/../escape']){const zip=zipSync({'Ogle-win32-x64/Ogle.exe':Buffer.from('x'),'Ogle-win32-x64/resources/app.asar':Buffer.from('y'),['Ogle-win32-x64/'+leaf]:Buffer.from('z')}),file=path.join(dir,'fixture.zip');await fs.writeFile(file,zip);await assert.rejects(validateDistributionZip(file),/Unsafe/);}}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('known user directory roots and profiles inside the application are refused',async()=>{for(const name of ['Downloads','Desktop','Documents'])if(process.env.USERPROFILE)await assert.rejects(assertInstallDirectory(path.join(process.env.USERPROFILE,name)),/location/);const f=await fixture();try{const staged=await f.manager.prepare(),install=path.join(f.dir,'installed');await fs.cp(staged.folder,install,{recursive:true});await assert.rejects(prepareHandoff({currentExe:path.join(install,'Ogle.exe'),stagedFolder:staged.folder,dataDir:path.join(install,'profile'),launch:false}),/profile is inside/);}finally{await f.cleanup();}});

test('truncated archive never reaches extraction',async()=>{const f=await fixture();try{f.metadata.assets[0].size++;await assert.rejects(f.manager.prepare(),/verification failed/);assert.equal(f.extracts,0);assert.deepEqual(await fs.readdir(path.join(f.dir,'updates')),[]);}finally{await f.cleanup();}});

test('verified ready update is reused and recovered across restarts without another ZIP download',async()=>{const f=await fixture();try{let downloads=0;const fetch=f.manager.fetcher;f.manager.fetcher=async(url,options)=>{if(url.endsWith('.zip'))downloads++;return fetch(url,options);};const first=await f.manager.prepare();assert.equal((await f.manager.prepare()).exePath,first.exePath);assert.equal(downloads,1);const restored=new UpdateManager({currentVersion:'0.7.5',dataDir:f.dir,fetcher:f.manager.fetcher,extractor:f.manager.extractor});const recovered=await restored.prepare();assert.equal(downloads,1);assert.equal(await restored.verifyReady(),true);assert.notEqual(recovered.exePath,first.exePath);await fs.writeFile(recovered.exePath,'tampered');assert.equal(await restored.verifyReady(),false);}finally{await f.cleanup();}});
test('editable recovery metadata cannot choose an arbitrary executable or escape the cache',async()=>{const f=await fixture();try{await f.manager.prepare();await fs.writeFile(path.join(f.dir,'updates','ready.json'),JSON.stringify({version:'0.7.6',stage:'../../outside',exePath:'C:/Windows/cmd.exe'}));const restored=new UpdateManager({currentVersion:'0.7.5',dataDir:f.dir,fetcher:f.manager.fetcher,extractor:f.manager.extractor});const ready=await restored.prepare();assert.ok(ready.exePath.startsWith(path.join(f.dir,'updates')));assert.notEqual(ready.exePath,'C:/Windows/cmd.exe');}finally{await f.cleanup();}});
test('a junction cache is refused without deleting its target',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-update-junction-'));try{const outside=path.join(dir,'outside'),profile=path.join(dir,'profile');await fs.mkdir(outside);await fs.mkdir(profile);await fs.writeFile(path.join(outside,'keep.txt'),'keep');await fs.symlink(outside,path.join(profile,'updates'),process.platform==='win32'?'junction':'dir');const manager=new UpdateManager({currentVersion:'0.7.5',dataDir:profile});await assert.rejects(manager.ensureDirectory(),/junction/);assert.equal(await fs.readFile(path.join(outside,'keep.txt'),'utf8'),'keep');}finally{await fs.rm(dir,{recursive:true,force:true});}});
