'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {prepareUserInstall,verifyInstalled,MARKER}=require('../src/main/user-install.cjs');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ogle-install-')),source=path.join(root,'portable'),dataDir=path.join(root,'profile'),localAppData=path.join(root,'local'),startMenuDirectory=path.join(root,'programs');await fs.mkdir(path.join(source,'resources'),{recursive:true});await fs.mkdir(dataDir);await fs.writeFile(path.join(source,'Ogle.exe'),Buffer.from('MZfixture executable'));await fs.writeFile(path.join(source,'resources','app.asar'),'fixture application');return {root,source,options:{currentExe:path.join(source,'Ogle.exe'),dataDir,localAppData,startMenuDirectory,desktopDirectory:path.join(root,'desktop'),version:'0.7.6',launch:false}};}
test('user installation stages a separate verified application without altering portable files or profile',async()=>{
 const f=await fixture();try{let plan;const result=await prepareUserInstall({...f.options,desktopShortcut:true,handoffPreparer:async options=>(plan=options,{target:options.targetDirectory})});assert.equal(plan.allowNewTarget,true);assert.equal(plan.targetDirectory,path.join(f.options.localAppData,'Ogle','Application'));assert.equal(plan.shortcuts.length,2);await verifyInstalled(result.stagedFolder);assert.equal(await fs.readFile(f.options.currentExe,'utf8'),'MZfixture executable');assert.deepEqual(await fs.readdir(f.options.dataDir),[]);}finally{await fs.rm(f.root,{recursive:true,force:true});}
});
test('existing foreign installations and profiles inside installation are rejected before replacement',async()=>{
 const f=await fixture();try{const target=path.join(f.options.localAppData,'Ogle','Application');await fs.mkdir(target,{recursive:true});await fs.writeFile(path.join(target,'unrelated.txt'),'preserve');await assert.rejects(prepareUserInstall({...f.options,handoffPreparer:async()=>{throw Error('must not run')}}));assert.equal(await fs.readFile(path.join(target,'unrelated.txt'),'utf8'),'preserve');await assert.rejects(prepareUserInstall({...f.options,dataDir:path.join(f.options.localAppData,'Ogle','profile')}),/separate/);}finally{await fs.rm(f.root,{recursive:true,force:true});}
});
test('managed installations require unchanged executable and ASAR before replacement',async()=>{
 const f=await fixture();try{const first=await prepareUserInstall({...f.options,handoffPreparer:async options=>({target:options.targetDirectory})});await fs.rename(first.stagedFolder,first.target);let called=false;await prepareUserInstall({...f.options,handoffPreparer:async options=>{called=true;assert.equal(options.allowNewTarget,false);return {target:options.targetDirectory};}});assert.equal(called,true);await fs.appendFile(path.join(first.target,'resources','app.asar'),'tampered');await assert.rejects(prepareUserInstall({...f.options,handoffPreparer:async()=>{}}),/changed/);assert.ok((await fs.readFile(path.join(first.target,MARKER),'utf8')).includes('Ogle'));}finally{await fs.rm(f.root,{recursive:true,force:true});}
});
test('failed handoff removes only its staging folder',async()=>{
 const f=await fixture();try{await assert.rejects(prepareUserInstall({...f.options,handoffPreparer:async()=>{throw Error('cancel fixture')}}),/cancel fixture/);const entries=await fs.readdir(path.join(f.options.localAppData,'Ogle'));assert.equal(entries.filter(name=>name.startsWith('.stage-')).length,0);assert.equal(await fs.readFile(f.options.currentExe,'utf8'),'MZfixture executable');}finally{await fs.rm(f.root,{recursive:true,force:true});}
});
