'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');
const invoke = (name, ...args) => ipcRenderer.invoke(`dock:${name}`, ...args);
contextBridge.exposeInMainWorld('dock', Object.freeze({
  setPinnedPanel: side => invoke('setPinnedPanel',side),
  windowShape: rects => invoke('windowShape',rects),
  activityStats: () => invoke('activityStats'),
  boot: () => invoke('boot'),
  listThreads: filters => invoke('listThreads', filters),
  readThread: id => invoke('readThread', id),
  startThread: cwd => invoke('startThread', cwd),
  sendTurn: (id, text, images = []) => invoke('sendTurn', id, text, images),
  steerTurn: (id,text,images=[],expectedTurnId) => invoke('steerTurn',id,text,images,expectedTurnId),
  interrupt: (id, turnId) => invoke('interrupt', id, turnId),
  respond: (id, result) => invoke('respond', id, result),
  saveSettings: patch => invoke('saveSettings', patch),
  chooseFolder: () => invoke('chooseFolder'),
  openChatGPT: action => invoke('openChatGPT', action),
  chatgptSend: payload => invoke('chatgptSend', payload),
  chatgptPaste: text => invoke('chatgptPaste',text),
  selectionMenu: text => invoke('selectionMenu',text),
  chatgptLayout: layout => invoke('chatgptLayout', layout),
  chatgptFind: (query, options = {}) => invoke('chatgptFind', query, options),
  chatgptStopFind: () => invoke('chatgptStopFind'),
  openCodex: id => invoke('openCodex', id),
  petMenu: () => invoke('petMenu'),
  petDrag: action => invoke('petDrag', action),
  codexAccount: () => invoke('codexAccount'),
  codexLogin: () => invoke('codexLogin'),
  codexLogout: () => invoke('codexLogout'),
  installPet: input => invoke('installPet', input),
  recommendedPets: () => invoke('recommendedPets'),
  listPets: () => invoke('listPets'),
  refreshPets: () => invoke('refreshPets'),
  petIcon: data=>invoke('petIcon',data),
  clipboardReadText: () => invoke('clipboardReadText'),
  clipboardWriteText: text => invoke('clipboardWriteText', text),
  editorOpen: () => invoke('editorOpen'),
  editorSave: options => invoke('editorSave', options),
  chooseShortcut: kind => invoke('chooseShortcut', kind),
  importShortcuts: payload => invoke('importShortcuts', payload),
  shortcutIcons: paths=>invoke('shortcutIcons',paths),
  droppedPaths: files => Array.from(files || []).map(file => webUtils.getPathForFile(file)).filter(Boolean),
  openShortcut: path => invoke('openShortcut', path),
  runCommand: text => invoke('runCommand', text),
  listWindowsTools: () => invoke('listWindowsTools'),
  openWindowsTool: id => invoke('openWindowsTool', id),
  searchFiles: (query,options) => invoke('searchFiles', query,options),
  readDirectory: path => invoke('readDirectory', path),
  terminalCreate: options => invoke('terminalCreate', options),
  terminalWrite: (id, data) => invoke('terminalWrite', id, data),
  terminalResize: (id, cols, rows) => invoke('terminalResize', id, cols, rows),
  terminalClose: id => invoke('terminalClose', id),
  terminalReleaseAdmin: () => invoke('terminalReleaseAdmin'),
  terminalAdminStatus: () => invoke('terminalAdminStatus'),
  terminalEnableAdmin: () => invoke('terminalEnableAdmin'),
  terminalDisableAdmin: () => invoke('terminalDisableAdmin'),
  windowAction: action => invoke('windowAction', action),
  windowTransition: (phase,mode,reducedMotion) => invoke('windowTransition',phase,mode,reducedMotion),
  onEvent: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('dock:event', listener);
    return () => ipcRenderer.removeListener('dock:event', listener);
  }
}));
