'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');
const invoke = (name, ...args) => ipcRenderer.invoke(`dock:${name}`, ...args);
contextBridge.exposeInMainWorld('dock', Object.freeze({
  setPinnedPanel: side => invoke('setPinnedPanel',side),
  panelFullscreen: enabled => invoke('panelFullscreen',enabled),
  chatgptZoom: factor => invoke('chatgptZoom',factor),
  windowShape: rects => invoke('windowShape',rects),
  activityStats: () => invoke('activityStats'),
  workspaceExport:snapshot=>invoke('workspaceExport',snapshot),workspaceImport:()=>invoke('workspaceImport'),workspaceSnapshot:()=>invoke('workspaceSnapshot'),workspaceSnapshots:()=>invoke('workspaceSnapshots'),workspaceRestore:token=>invoke('workspaceRestore',token),
  installationStatus:()=>invoke('installationStatus'),installForUser:options=>invoke('installForUser',options),
  checkUpdates:()=>invoke('checkUpdates'),prepareUpdate:()=>invoke('prepareUpdate'),installUpdate:()=>invoke('installUpdate'),
  boot: () => invoke('boot'),
  listModels: () => invoke('listModels'),
  claudeStatus:()=>invoke('claudeStatus'),
  claudeListThreads:()=>invoke('claudeListThreads'),
  claudeCreate:options=>invoke('claudeCreate',options),
  claudeWrite:(id,data)=>invoke('claudeWrite',id,data),
  claudeResize:(id,cols,rows)=>invoke('claudeResize',id,cols,rows),
  claudeClose:id=>invoke('claudeClose',id),
  historyMenu:target=>invoke('historyMenu',target),
  renameConversation:(provider,id,name)=>invoke('renameConversation',provider,id,name),
  removeConversation:(provider,id)=>invoke('removeConversation',provider,id),
  listArchivedConversations:provider=>invoke('listArchivedConversations',provider),
  restoreConversation:(provider,id)=>invoke('restoreConversation',provider,id),
  openClaudeWeb:action=>invoke('openClaudeWeb',action),
  claudeWebLayout:layout=>invoke('claudeWebLayout',layout),
  claudeWebZoom:factor=>invoke('claudeWebZoom',factor),
  claudeWebFind:(query,options)=>invoke('claudeWebFind',query,options),
  claudeWebStopFind:()=>invoke('claudeWebStopFind'),
  listThreads: filters => invoke('listThreads', filters),
  readRuntime: id=>invoke('readRuntime',id),
  readThread: (id, options) => invoke('readThread', id, options),
  startThread: cwd => invoke('startThread', cwd),
  sendTurn: (id, text, images = [],options={}) => invoke('sendTurn', id, text, images,options),
  steerTurn: (id,text,images=[],expectedTurnId) => invoke('steerTurn',id,text,images,expectedTurnId),
  interrupt: (id, turnId) => invoke('interrupt', id, turnId),
  respond: (id, result) => invoke('respond', id, result),
  saveSettings: patch => invoke('saveSettings', patch),
  chooseFolder: () => invoke('chooseFolder'),
  openChatGPT: action => invoke('openChatGPT', action),
  chatgptSend: payload => invoke('chatgptSend', payload),
  chatgptPaste: text => invoke('chatgptPaste',text),
  selectionMenu: text => invoke('selectionMenu',text),
  chatgptLayout: layout => invoke('chatgptLayout', layout),
  chatgptFind: (query, options = {}) => invoke('chatgptFind', query, options),
  chatgptStopFind: () => invoke('chatgptStopFind'),
  openCodex: id => invoke('openCodex', id),
  petMenu: () => invoke('petMenu'),
  petDrag: action => invoke('petDrag', action),
  codexAccount: () => invoke('codexAccount'),
  codexLogin: () => invoke('codexLogin'),
  codexLogout: () => invoke('codexLogout'),
  installPet: input => invoke('installPet', input),
  recommendedPets: () => invoke('recommendedPets'),
  listPets: () => invoke('listPets'),
  refreshPets: () => invoke('refreshPets'),
  petIcon: data=>invoke('petIcon',data),
  clipboardReadText: () => invoke('clipboardReadText'),
  clipboardWriteText: text => invoke('clipboardWriteText', text),
  editorOpen: () => invoke('editorOpen'),
  editorSave: options => invoke('editorSave', options),
  chooseShortcut: kind => invoke('chooseShortcut', kind),
  importShortcuts: payload => invoke('importShortcuts', payload),
  shortcutIcons: paths=>invoke('shortcutIcons',paths),
  droppedPaths: files => Array.from(files || []).map(file => webUtils.getPathForFile(file)).filter(Boolean),
  openShortcut: path => invoke('openShortcut', path),
  runCommand: text => invoke('runCommand', text),
  listWindowsTools: () => invoke('listWindowsTools'),
  openWindowsTool: id => invoke('openWindowsTool', id),
  searchFiles: (query,options) => invoke('searchFiles', query,options),
  readDirectory: path => invoke('readDirectory', path),
  terminalCreate: options => invoke('terminalCreate', options),
  terminalWrite: (id, data) => invoke('terminalWrite', id, data),
  terminalResize: (id, cols, rows) => invoke('terminalResize', id, cols, rows),
  terminalClose: id => invoke('terminalClose', id),
  terminalReleaseAdmin: () => invoke('terminalReleaseAdmin'),
  terminalAdminStatus: () => invoke('terminalAdminStatus'),
  terminalEnableAdmin: () => invoke('terminalEnableAdmin'),
  terminalDisableAdmin: () => invoke('terminalDisableAdmin'),
  windowAction: action => invoke('windowAction', action),
  windowTransition: (phase,mode,reducedMotion) => invoke('windowTransition',phase,mode,reducedMotion),
  onEvent: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('dock:event', listener);
    return () => ipcRenderer.removeListener('dock:event', listener);
  }
}));
