'use strict';
const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {validatePatch}=require('./settings.cjs'),{durableWrite}=require('./durable-file.cjs');
const MAX_BYTES=20*1024*1024,ID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const EXCLUDED=['Browser sessions and cookies','Credentials and authentication','Administrator privileges','Windows startup registration','Unknown preferences'];
// Known validated settings are portable except startup/elevation/auth. Unknown
// local preferences remain in the existing profile and never enter the archive.
function portableSettings(value){const result={};for(const [key,item]of Object.entries(value||{})){if(key==='autoStart'||/admin|password|token|cookie|credential|session|auth/i.test(key))continue;const clean=validatePatch({[key]:item});Object.assign(result,clean);}return result;}
function parseBackup(bytes){if(Buffer.byteLength(bytes)>MAX_BYTES)throw new Error('Workspace backup exceeds 20 MB.');let doc;try{doc=JSON.parse(bytes.toString());}catch{throw new Error('Workspace backup is not valid JSON.');}if(!doc||doc.format!=='ogle-workspace'||doc.version!==1||!doc.settings||typeof doc.settings!=='object'||Array.isArray(doc.settings))throw new Error('Unsupported workspace backup.');const patch=portableSettings(doc.settings);if(!Object.keys(patch).length)throw new Error('Workspace backup contains no supported settings.');return {doc,patch};}
function summary(patch){return {noteCharacters:patch.note?.length||0,drafts:Object.keys(patch.drafts||{}).length,editorTabs:patch.editorTabs?.length||0,links:patch.shortcuts?.length||0,preferences:Object.keys(patch).length};}
function readBounded(file){const stat=fs.statSync(file);if(!stat.isFile()||stat.size>MAX_BYTES)throw new Error('Choose a workspace backup file smaller than 20 MB.');return fs.readFileSync(file);}
class WorkspaceBackups{
 constructor(store){this.store=store;this.previews=new Map();this.directory=path.join(path.dirname(store.file),'workspace-recovery');}
 async exportToAsync(file,snapshot){if(snapshot!==undefined&&(!snapshot||typeof snapshot!=='object'||Array.isArray(snapshot)))throw new Error('Invalid live workspace snapshot.');if(typeof file!=='string'||!path.isAbsolute(file))throw new Error('Choose a backup destination.');return this.store.workerTask('backup-export',{target:file,...(snapshot===undefined?{}:{snapshot})});}
 async previewFileAsync(file){const result=await this.store.workerTask('backup-preview',{target:file});const patch=result.patch;delete result.patch;this.previews.set(result.token,{patch,at:Date.now()});while(this.previews.size>10)this.previews.delete(this.previews.keys().next().value);return result;}
 snapshotAsync(){return this.store.workerTask('backup-snapshot');}
 listSnapshotsAsync(){return this.store.workerTask('backup-list');}
 async importPreviewAsync(token){const preview=this.previews.get(token);if(!preview||Date.now()-preview.at>600000)throw new Error('Backup preview expired. Preview the file again.');const patch=structuredClone(preview.patch);if(patch.editorTabs)patch.editorTabs=patch.editorTabs.map(tab=>({...tab,path:'',dirty:true}));const rollback=await this.snapshotAsync();const settings=await this.store.updateAsync(patch);this.previews.delete(token);return {settings,rollbackToken:rollback.token,summary:summary(patch)};}
 async rollbackAsync(token){if(typeof token!=='string'||!ID.test(token))throw new Error('Invalid workspace snapshot.');const patch=await this.store.workerTask('backup-read',{target:token});const recovery=await this.snapshotAsync();return {settings:await this.store.updateAsync(patch),restored:true,rollbackToken:recovery.token};}
 document(){return {format:'ogle-workspace',version:1,createdAt:new Date().toISOString(),settings:portableSettings(this.store.value)};}
 exportTo(file){if(typeof file!=='string'||!path.isAbsolute(file))throw new Error('Choose a backup destination.');const text=JSON.stringify(this.document(),null,2);if(Buffer.byteLength(text)>MAX_BYTES)throw new Error('Workspace backup exceeds 20 MB.');durableWrite(file,text);return {file,summary:summary(this.document().settings),excluded:EXCLUDED};}
 previewFile(file){const {patch}=parseBackup(readBounded(file));const token=randomUUID();this.previews.set(token,{patch,at:Date.now()});for(const [id,item]of this.previews)if(Date.now()-item.at>600000)this.previews.delete(id);while(this.previews.size>10)this.previews.delete(this.previews.keys().next().value);return {token,summary:summary(patch),excluded:EXCLUDED,warning:'Import replaces the included workspace preferences and content. Browser sign-ins and administrator access stay on this PC. Imported editor buffers open as unsaved copies.'};}
 assertDirectory(){fs.mkdirSync(this.directory,{recursive:true});if(fs.lstatSync(this.directory).isSymbolicLink()||fs.realpathSync(this.directory)!==path.resolve(this.directory))throw new Error('Unsafe workspace recovery directory.');}
 snapshot(){const text=JSON.stringify(this.document(),null,2);if(Buffer.byteLength(text)>MAX_BYTES)throw new Error('Workspace snapshot exceeds 20 MB.');this.assertDirectory();const token=randomUUID(),file=path.join(this.directory,token+'.json');durableWrite(file,text);return {token,file,createdAt:new Date().toISOString()};}
 importPreview(token){const preview=this.previews.get(token);if(!preview||Date.now()-preview.at>600000)throw new Error('Backup preview expired. Preview the file again.');const patch=structuredClone(preview.patch);if(patch.editorTabs)patch.editorTabs=patch.editorTabs.map(tab=>({...tab,path:'',dirty:true}));const rollback=this.snapshot();this.store.update(patch);this.previews.delete(token);return {settings:this.store.value,rollbackToken:rollback.token,summary:summary(patch)};}
 listSnapshots(){if(!fs.existsSync(this.directory))return {snapshots:[]};this.assertDirectory();const snapshots=[];for(const name of fs.readdirSync(this.directory)){const token=name.replace(/\.json$/,'');if(!ID.test(token)||!name.endsWith('.json'))continue;try{const file=path.join(this.directory,name);if(fs.lstatSync(file).isSymbolicLink()||fs.realpathSync(file)!==path.resolve(file))continue;const {doc,patch}=parseBackup(readBounded(file));snapshots.push({token,createdAt:doc.createdAt,summary:summary(patch)});}catch{}}return {snapshots:snapshots.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))};}
 rollback(token){if(typeof token!=='string'||!ID.test(token))throw new Error('Invalid workspace snapshot.');this.assertDirectory();const file=path.join(this.directory,token+'.json');if(fs.lstatSync(file).isSymbolicLink()||fs.realpathSync(file)!==path.resolve(file))throw new Error('Unsafe workspace snapshot path.');const {patch}=parseBackup(readBounded(file));const recovery=this.snapshot();return {settings:this.store.update(patch),restored:true,rollbackToken:recovery.token};}
}
module.exports={WorkspaceBackups,portableSettings,parseBackup,MAX_BYTES};
