'use strict';
const { _electron: electron } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const targetThreadId = process.env.PETDOCK_SMOKE_THREAD_ID?.trim();
  assert.ok(targetThreadId, 'Set PETDOCK_SMOKE_THREAD_ID to an explicitly authorized, idle smoke-test task before running this test.');
  const root = path.resolve(__dirname, '..'), output = path.join(root, 'artifacts');
  const fixture = path.join(output, 'feature-fixtures');
  fs.mkdirSync(fixture, { recursive: true });
  fs.writeFileSync(path.join(fixture, 'example.json'), '{"original":true}\n');
  const profile=path.join(output,`features-profile-${Date.now()}`);fs.mkdirSync(profile,{recursive:true});
  fs.writeFileSync(path.join(profile,'settings.json'),JSON.stringify({lastThreadId:targetThreadId,autoExpand:false}));
  const env = { ...process.env, PETDOCK_DATA_DIR: profile };
  delete env.ELECTRON_RUN_AS_NODE;
  const app = await electron.launch({ args: [root], env });
  try {
    const page = await app.firstWindow(), errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.waitForFunction(() => document.querySelector('#status-dot').classList.contains('ready'), null, { timeout: 60000 });
    await page.locator('[data-panel="editor"]').evaluate(el => el.click());
    await page.waitForFunction(() => !document.body.classList.contains('collapsed'));
    await app.evaluate(({ dialog }, folder) => {
      dialog.showOpenDialog = async (_window, options) => ({ canceled: false, filePaths: [options.properties.includes('openDirectory') ? folder : `${folder}/example.json`] });
      dialog.showSaveDialog = async () => ({ canceled: false, filePath: `${folder}/saved.json` });
      dialog.showMessageBox = async (_window,options) => {if(options.message==='Choose a link target')return {response:1};throw new Error(`Unexpected smoke-test dialog: ${options.message}`);};
    }, fixture.replace(/\\/g, '/'));
    await page.locator('[data-panel="editor"]').click();
    await page.locator('#editor-panel').getByRole('button', { name: 'Open…', exact: true }).click();
    await page.locator('.editor-language').selectOption('json');
    const editor = page.locator('.cm-content');
    await editor.click();
    await page.keyboard.press('Control+a');
    await page.keyboard.insertText('{"dock":42}');
    await page.locator('#editor-panel').getByRole('button', { name: 'Save as…', exact: true }).click();
    await page.waitForTimeout(500);
    assert.equal(fs.readFileSync(path.join(fixture, 'saved.json'), 'utf8'), '{"dock":42}');
    await page.keyboard.press('Escape');
    await page.screenshot({ path: path.join(output, 'feature-editor.png') });
    await editor.click();
    await page.keyboard.press('Control+a');
    await page.keyboard.insertText('{"unsaved":true}');
    await page.waitForTimeout(700);
    const persisted = await page.evaluate(() => window.dock.boot());
    assert.ok(persisted.settings.editorTabs.some(tab => tab.text === '{"unsaved":true}' && tab.dirty));
    await page.locator('[data-panel="shortcuts"]').click();
    await page.locator('#shortcuts-panel').getByRole('button', { name: '＋ Add', exact: true }).click();
    await page.locator('#shortcuts-panel').getByRole('button',{name:'Choose file or folder…',exact:true}).click();
    await page.locator('#shortcuts-panel button[title="Browse folder"]').last().click();
    await page.locator('.links-folder-tree').getByRole('button',{name:/example\.json/}).waitFor();
    await page.screenshot({ path: path.join(output, 'feature-shortcuts.png') });
    await page.locator('[data-panel="terminal"]').click();
    await page.evaluate(()=>{window.testTerminalOutput='';window.dock.onEvent(event=>{if(event.type==='terminal'&&event.event==='data')window.testTerminalOutput+=event.data;});});
    await page.locator('#terminal-panel').getByRole('button', { name: '+ CMD', exact: true }).click();
    await page.locator('.terminal-tabs button').first().waitFor();
    const termInput = page.locator('.terminal-session:not([hidden]) .xterm-helper-textarea');
    await termInput.focus();
    await page.keyboard.type('set /a PETDOCK_TERMINAL_SUM=6*7');
    await page.keyboard.press('Enter');
    await page.keyboard.type('echo PETDOCK_TERMINAL_UI_%PETDOCK_TERMINAL_SUM%');
    await page.keyboard.press('Enter');
    await page.waitForFunction(()=>window.testTerminalOutput.includes('PETDOCK_TERMINAL_UI_42'),null,{timeout:15000});
    await page.screenshot({ path: path.join(output, 'feature-terminal.png') });
    await page.locator('#terminal-panel').getByRole('button', { name: 'Close session', exact: true }).click();
    await page.locator('[data-panel="chats"]').click();
    const selected=await page.evaluate(()=>state.selected?.id);
    assert.equal(selected,targetThreadId,'Only the explicitly authorized isolated desktop-owned task may receive the test prompt');
    const read=await page.evaluate(id=>window.dock.readThread(id),targetThreadId);
    assert.equal(read.thread.id,targetThreadId);
    assert.equal(Boolean(read.runtime?.running),false,'Isolated test task must be idle before smoke send');
    await page.waitForFunction(() => document.querySelector('#activity').textContent !== 'Loading conversation…');
    const marker = `PETDOCK_ENTER_OK_${Date.now()}`;
    await page.locator('#prompt').fill(`Reply exactly ${marker}. Do not use tools or change files.`);
    assert.equal(await page.locator('#send').isEnabled(), true);
    await page.locator('#prompt').press('Enter');
    await page.waitForFunction(expected => [...document.querySelectorAll('.message.assistant .message-text')].some(el => el.textContent.trim() === expected), marker, { timeout: 120000 });
    await page.waitForFunction(() => document.querySelector('#stop').hidden, null, { timeout: 30000 });
    assert.equal(await page.locator('#prompt').inputValue(), '');
    assert.deepEqual(errors, []);
    await page.screenshot({ path: path.join(output, 'feature-codex.png') });
    const report = { at: new Date().toISOString(), editorSavedRealFile: true, unsavedEditorPersisted: true, folderTree: true, embeddedCmd: true, enterSentAndReceived: marker, targetThreadId, profile, rendererErrors: errors };
    fs.writeFileSync(path.join(output, 'features-smoke.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
