import { EditorView, basicSetup } from 'codemirror';
import { Compartment, Prec } from '@codemirror/state';
import { keymap } from '@codemirror/view';
import { acceptCompletion, completionStatus, startCompletion } from '@codemirror/autocomplete';
import { indentWithTab } from '@codemirror/commands';
import { StreamLanguage } from '@codemirror/language';
import { oneDark } from '@codemirror/theme-one-dark';
import { javascript } from '@codemirror/lang-javascript';
import { json, jsonParseLinter } from '@codemirror/lang-json';
import { linter, lintGutter } from '@codemirror/lint';
import { python } from '@codemirror/lang-python';
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
import { markdown } from '@codemirror/lang-markdown';
import { shell } from '@codemirror/legacy-modes/mode/shell';
import { c, csharp } from '@codemirror/legacy-modes/mode/clike';
import { vb } from '@codemirror/legacy-modes/mode/vb';
import { powerShell as powershell } from '@codemirror/legacy-modes/mode/powershell';
import { cpp } from '@codemirror/lang-cpp';
import { sql } from '@codemirror/lang-sql';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
const batch = { token(stream) {
  if(stream.sol() && stream.match(/\s*(?:rem\b|::).*/i))return 'comment';
  if(stream.match(/%[^%\s]+%|![^!\s]+!|%[0-9*]|%%[a-z]/i))return 'variableName';
  if(stream.match(/"[^"]*"/))return 'string';
  if(stream.match(/\b(?:echo|set|if|else|for|in|do|goto|call|exit|shift|setlocal|endlocal|pause|cd|pushd|popd|copy|move|del|mkdir|rmdir|dir|start)\b/i))return 'keyword';
  if(stream.match(/[&|><^]+/))return 'operator';stream.next();return null;
}};
window.PetDockVendors = { EditorView, basicSetup, Compartment, Prec, keymap, acceptCompletion, completionStatus, startCompletion, indentWithTab, StreamLanguage, oneDark, javascript, json, jsonParseLinter, linter, lintGutter, python, html, css, markdown, shell, c, cpp, csharp, vb, batch, sql, powershell, Terminal, FitAddon };
