'use strict';
window.OgleWorkspaceTools=(()=>{
  let options,status,updateStatus,download,restart,busy=false;
  const node=(tag,text)=>{const element=document.createElement(tag);if(text)element.textContent=text;return element;};
  function mount(root,configuration){
    options=configuration;
    const backup=node('section');backup.className='settings-section';backup.append(node('h2','Workspace and recovery'),node('p','Back up notes, drafts, editor buffers, Links and preferences as plain JSON. Browser sign-ins stay on this PC.'));
    status=node('p',options.recovery?.message||'Changes are saved locally while you type.');status.className='settings-hint';status.setAttribute('role','status');
    const actions=node('div');actions.className='settings-actions';
    const action=(text,run)=>{const button=node('button',text);button.onclick=()=>execute(run);return button;};
    actions.append(action('Export',async()=>{const result=await options.api.workspaceExport(options.capture());if(!result.cancelled)status.textContent='Workspace exported.';}),action('Import',async()=>{await options.flush();const result=await options.api.workspaceImport();if(!result.cancelled){options.restore(result.settings);status.textContent='Workspace restored. A recovery copy was kept.';}}),action('Save recovery copy',async()=>{await options.flush();await options.api.workspaceSnapshot();status.textContent='Recovery copy saved.';}),action('Recovery copies…',showRecovery));backup.append(actions,status);root.append(backup);
    const installation=node('section');installation.className='settings-section';installation.append(node('h2','Install on this PC'));const installStatus=node('p','Checking installation…');installStatus.className='settings-hint';const desktop=node('input');desktop.type='checkbox';const desktopLabel=node('label','Desktop shortcut ');desktopLabel.append(desktop);const install=node('button','Install and restart');install.hidden=true;install.onclick=async()=>{install.disabled=true;try{await options.api.installForUser({desktopShortcut:desktop.checked});}catch(error){options.report(error);install.disabled=false;}};installation.append(installStatus,desktopLabel,install);root.append(installation);if(options.api.installationStatus)options.api.installationStatus().then(result=>{installStatus.textContent=result.installed?'Installed for your Windows account.':'Install without administrator access; your workspace and sign-ins stay in place.';install.hidden=!result.available||result.installed;desktopLabel.hidden=install.hidden;}).catch(options.report);else{installStatus.textContent='Installation is available in the Windows build.';desktopLabel.hidden=true;}
    const updates=node('section');updates.className='settings-section';updates.append(node('h2','Updates'));updateStatus=node('p','Check for a verified Windows update.');updateStatus.className='settings-hint';updateStatus.setAttribute('role','status');const controls=node('div');controls.className='settings-actions';
    const check=node('button','Check updates');check.onclick=async()=>{check.disabled=true;try{const result=await options.api.checkUpdates();updateStatus.textContent=result.available?'Ogle '+result.version+' is available.':'Ogle '+result.currentVersion+' is up to date.';download.hidden=!result.available;}catch(error){options.report(error);}finally{check.disabled=false;}};
    download=node('button','Download update');download.hidden=true;download.onclick=async()=>{download.disabled=true;try{const result=await options.api.prepareUpdate();if(result.ready){download.hidden=true;restart.hidden=false;updateStatus.textContent='Ogle '+result.version+' is ready. Restart after finishing work.';}}catch(error){options.report(error);}finally{download.disabled=false;}};
    restart=node('button','Restart to update');restart.hidden=true;restart.onclick=async()=>{restart.disabled=true;try{await options.api.installUpdate();}catch(error){options.report(error);restart.disabled=false;}};controls.append(check,download,restart);updates.append(controls,updateStatus);root.append(updates);
  }
  async function execute(run){if(busy)return;busy=true;options.operation(true);try{await run();}catch(error){options.report(error);}finally{busy=false;options.operation(false);}}
  async function showRecovery(){
    const result=await options.api.workspaceSnapshots();const dialog=node('dialog');dialog.className='history-dialog';dialog.append(node('h3','Recovery copies'));if(!result.snapshots.length)dialog.append(node('p','No recovery copies yet.'));
    const close=()=>{dialog.remove();options.layout();};for(const snapshot of result.snapshots){const row=node('div');row.append(node('span',new Date(snapshot.createdAt).toLocaleString()));const restore=node('button','Restore');restore.onclick=()=>execute(async()=>{await options.flush();const restored=await options.api.workspaceRestore(snapshot.token);if(!restored.cancelled){options.restore(restored.settings);status.textContent='Recovery copy restored.';close();}});row.append(restore);dialog.append(row);}const cancel=node('button','Close');cancel.onclick=close;dialog.addEventListener('cancel',close);dialog.append(cancel);document.body.append(dialog);dialog.showModal();options.layout();
  }
  function progress(event){if(!updateStatus)return;if(event.phase==='downloading')updateStatus.textContent='Downloading · '+Math.floor(event.received/event.total*100)+'%';else if(event.phase==='extracting')updateStatus.textContent='Verifying and preparing the update…';else if(event.phase==='ready')updateStatus.textContent='Ogle '+event.version+' is ready to restart.';}
  function close(){document.querySelectorAll('dialog.history-dialog').forEach(dialog=>dialog.remove());options?.layout();}
  return{mount,progress,close};
})();
